### ISSUE TITLE
"The tokenizer class you load from this checkpoint is 'LLaMATokenizer'."

### ISSUE THREAD

**Issue by Gitterman69** [lxe/simple-llm-finetuner#40]
```
(llama) user@DESKTOP-CR45CKF:~/simple-llm-finetuner$ python app.py

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /home/user/anaconda3/envs/llama/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/user/anaconda3/envs/llama/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/llama/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/anaconda3/envs/llama/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/home/user/anaconda3/envs/llama/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/anaconda3/envs/llama/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/anaconda3/envs/llama/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/anaconda3/envs/llama/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/user/anaconda3/envs/llama/lib/python3.10/site-packages/gradio/helpers.py", line 587, in tracked_fn
    response = fn(*args)
  File "/home/user/simple-llm-finetuner/app.py", line 130, in train
    self.trainer.train(
  File "/home/user/simple-llm-finetuner/trainer.py", line 172, in train
    assert self.model is not None
AssertionError
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'.
The class this function is called from is 'LlamaTokenizer'.
Killed
```

**Comment by TheMixu** [comment]
[This might help you](https://github.com/huggingface/transformers/issues/22222#issuecomment-1477171703)

**Comment by lxe** [comment]
The llamaTokenizer warning is unrelated. The other error happens if you don't select the model. Select the base model and hit train again.

**Comment by lxe** [comment]
The "Killed" that you're seeing is most certainly the machine's OS killing the process due to exhausting the available memory. Not sure why this would be doing it if the model isn't loaded.
