### ISSUE TITLE
RuntimeError: unscale_() has already been called on this optimizer since the last update().

### ISSUE THREAD

**Issue by junxu-ai** [lxe/simple-llm-finetuner#54]
The error message is attached below:

Parameter 'function'=<function Trainer.tokenize_training_text.<locals>.<lambda> at 0x7f8eb04d5c60> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.
You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
{'loss': 2.4296, 'learning_rate': 0.0002901960784313725, 'epoch': 0.1}
{'loss': 2.271, 'learning_rate': 0.0002803921568627451, 'epoch': 0.2}
{'loss': 2.2099, 'learning_rate': 0.0002705882352941176, 'epoch': 0.29}
{'loss': 2.2199, 'learning_rate': 0.00026078431372549016, 'epoch': 0.39}
{'loss': 2.1911, 'learning_rate': 0.00025098039215686274, 'epoch': 0.49}
{'loss': 2.2129, 'learning_rate': 0.00024117647058823527, 'epoch': 0.59}
{'loss': 2.1752, 'learning_rate': 0.00023137254901960783, 'epoch': 0.68}
{'loss': 2.1841, 'learning_rate': 0.0002215686274509804, 'epoch': 0.78}
{'loss': 2.1827, 'learning_rate': 0.00021176470588235295, 'epoch': 0.88}
{'loss': 2.1514, 'learning_rate': 0.00020196078431372548, 'epoch': 0.98}
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gradio/blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gradio/helpers.py", line 602, in tracked_fn
    response = fn(*args)
  File "/home/user/app/app.py", line 131, in train
    self.trainer.train(
  File "/home/user/app/trainer.py", line 273, in train
    result = self.trainer.train(resume_from_checkpoint=False)
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/transformers/trainer.py", line 1850, in _inner_training_loop
    self.accelerator.clip_grad_norm_(
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/accelerate/accelerator.py", line 1913, in clip_grad_norm_
    self.unscale_gradients()
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/accelerate/accelerator.py", line 1876, in unscale_gradients
    self.scaler.unscale_(opt)
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 275, in unscale_
    raise RuntimeError("unscale_() has already been called on this optimizer since the last update().")
RuntimeError: unscale_() has already been called on this optimizer since the last update().

**Comment by junxu-ai** [comment]
fixed with a special version of transformers. 

git+https://github.com/huggingface/transformers@de9255de27abfcae4a1f816b904915f0b1e23cd9
--

**Comment by junxu-ai** [comment]
as it works, i considered it closed. thanks.

**Comment by lkmdhertg** [comment]
Unfortunately, the link provided does not work anymore. Without having access to this link, I still get the error. Could you kindly provide another link to the mentioned "special version of transformers" or describe what to do to fix the problem?
Thank you!
